name: cd

on:
  push:
    branches: main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    container: node
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Build üîß
        run: |
          npm install
          npx ng build --prod

      - name: Deploy üöÄ
        env:
          DIR_TO_PUBLISH: dist
          ORG_NAME: codelab-dev
          REPO_NAME: codelab-dev.github.io
          USER_NAME: Alexandr Kolesov
          USER_EMAIL: kolesov.alex.s@gmail.com
        run: |
          # Clone
          git clone https://${{ secrets.GH_USER }}:${{ secrets.GH_PAT }}@github.com/${{ env.ORG_NAME }}/${{ env.REPO_NAME }}
          
          # Update content
          rm -rf ${{ env.REPO_NAME }}/*
          cp ${{ env.DIR_TO_PUBLISH }}/* ${{ env.REPO_NAME }}

          # Commit and push
          cd ${{ env.REPO_NAME }}
          git config user.name ${{ env.USER_NAME }}
          git config user.email ${{ env.USER_EMAIL }}
          git add .
          git commit -m "New version"
          git push
