name: cd

on:
  push:
    branches:
    - main
    - ghp-new

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    container: node
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

#       - name: Build ðŸ”§
#         run: |
#           npm install
#           npx ng build --prod --base-href=/codelab-ng/codelab-ng/ # Slash at the end is important. It allows not to specify --deploy-url and fixes favicon.
          
#       - name: Deploy ðŸš€
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: dist

      - name: Deploy ðŸš€
        env:
          DIR_TO_PUBLISH: build
          ORG_NAME: codelab-dev
          REPO_NAME: codelab-dev.github.io
          UESER_NAME: Alexandr Kolesov
          USER_EMAIL: kolesov.alex.s@gmail.com
        run: |
          echo "hello, world" > index.html
        
          # Clone and clean
          git clone https://{{ secrets.GH_USER }}:{{ secrets.GH_PAT }}@github.com/$ORG_NAME/$REPO_NAME
          rm -rf $REPO_NAME/*
          
          # Copy
          cp index.html $REPO_NAME

          # Commit and push
          cd $REPO_NAME
          git config user.name $USER_NAME
          git config user.email $USER_EMAIL
          git commit -m "New version"
          git push
